# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
require 'open-uri'
require 'nokogiri'
require 'date'

User.delete_all
Post.delete_all



User.create( email: "admin@hiki.com",
             username: "Admin",
             password: "hiki1234567890",
             password_confirmation: "hiki1234567890",
             )


# Post.create( user_id: User.first.id,
#              post_title: Faker::Name.title,
#              post_text: Faker::Lorem.paragraph(4),
#              post_date: Date.today-rand(10000)
#              )


# url = "http://simple.wikipedia.org/wiki/Attack_on_Pearl_Harbor"
# agent = Mechanize.new
# page = agent.get(url)

# pages_to_scrub = page.links

# pages_to_scrub.each do |link|
#   begin
#     temp = agent.get(link)
#     if temp.code.match('200')
#       temp = link.click
#       url = temp.uri.to_s
#       page = Nokogiri::HTML(open(url))
#       page_text = page.css("div.mw-content-ltr > p:first").text()
#       page_text.gsub!(/(\[.])/, "")
#       temp_date = page.css("table td:nth-child(2)")[0]
#       if temp_date != nil
#         date = page.css("table td:nth-child(2)")[0].text()
#         d = date.match(/\d{4}/)
#         d = d.to_s
#         d.insert(0,"1 January ")
#         # new_date = Chronic.parse(d)
#         nd = Date.parse(d)
#       end
#     end

#     Post.create(
#       user_id: User.first.id,
#       post_title: page.css("#firstHeading").inner_text(),
#       post_text: page_text,
#       post_date: nd
#     )
#   rescue Mechanize::ResponseCodeError => e
#     puts e.to_s
#     next
#   end
# end





a={
  "1801"=> "Giuseppe Piazzi discovers the dwarf planet Ceres.",
  "1801"=> "Thomas Jefferson elected President of the United States by the House of Representatives, following a tie in the Electoral College",
  "1801"=> "The Kingdom of Great Britain and the Kingdom of Ireland merge to form the United Kingdom.",
  "1801"=> "Ranjit Singh crowned as King of Punjab.",
  "1801"=> "Napoleon signs the Concordat of 1801 with the Pope.",
  "1801"=> "Cairo falls to the British.",
  "1801"=> "Assassination of Tsar Paul I of Russia.",
  "1801"=> "British defeat French at the Second Battle of Abukir",
  "1801"=> "the First Barbary War and the Second Barbary War between the United States and the Barbary States of North Africa",
  "1802"=> "Treaty of Amiens between France and the United Kingdom ends the War of the Second Coalition.",
  "1802"=> "Ludwig van Beethoven performs his Moonlight Sonata for the first time.",
  "1803"=> "The United States more than doubles in size when it buys out France's territorial claims in North America via the Louisiana Purchase.",
  "1803"=> "The Wahhabis of the First Saudi State capture Mecca and Medina.",
  "1803"=> "War breaks out between Britain and France; this is considered by some to be the beginning of the Napoleonic Wars.",
  "1803"=> "First phase of Padri War. (to 1825)",
  "1804"=> "Haiti gains independence from France and becomes the first black republic.",
  "1804"=> "Russo-Persian War.",
  "1804"=> "Austrian Empire founded by Francis I.",
  "1804"=> "Napoleon crowns himself Emperor of the French.",
  "1804"=> "World population reaches 1 billion.",
  "1804"=> "First steam locomotive begins operation.",
  "1804"=> "Morphine first isolated.",
  "1804"=> "Fulani Jihad in Nigeria.",
  "1804"=> "Serbian revolution erupts against the Ottoman rule. Suzerainty of Serbia recognized in 1817.",
  "1805"=> "The Battle of Trafalgar eliminates the French and Spanish naval fleets and allows for British dominance of the seas, a major factor for the success of the British Empire later in the century.",
  "1805"=> "Napoleon decisively defeats an Austrian-Russian army at the Battle of Austerlitz.",
  "1805"=> "Muhammad Ali modernizes Egypt.",
  "1806"=> "Holy Roman Empire dissolved as a consequence of the Treaty of Pressburg.",
  "1806"=> "Cape Colony becomes part of the British Empire.",
  "1806"=> "Russo-Turkish War, Treaty of Bucharest.",
  "1807"=> "Britain declares the Slave Trade illegal.",
  "1808"=> "Beethoven performs his Fifth Symphony",
  "1808"=> "Russia conquers Finland from Sweden in the Finnish War.",
  "1808"=> "Spanish guerrillas fight in the Peninsular War.",
  "1808"=> "Herman Willem Daendels the Governor-general of the Dutch East Indies (1808) begin the construction of Java Great Post Road.",
  "1809"=> "Napoleon strips the Teutonic Knights of their last holdings in Bad Mergentheim.",
  "1819"=> "29 January, Stamford Raffles arrives in Singapore with William Farquhar to establish a trading post for the British East India Company.",
  "1810"=> "The University of Berlin was founded. Among its students and faculty are Hegel, Marx, and Bismarck.",
  "1810"=> "The Grito de Dolores begins the Mexican War of Independence.",
  "1810"=> "The Trumpet gets valves.",
  "1810"=> "Most of the Latin American colonies free themselves from the Spanish and Portuguese Empires after the Latin American wars of independence.",
  "1812"=> "The French invasion of Russia is a turning point in the Napoleonic Wars.",
  "1812"=> "War of 1812 between the United States and Canada (with assistance from the United Kingdom)",
  "1813"=> "Jane Austen publishes Pride and Prejudice",
  "1814"=> "Napoleon abdicates and is exiled to Elba.",
  "1814"=> "Elisha Haydon Collier invents the Flintlock Revolver.",
  "1813"=> "The contest between the British Empire and Imperial Russia for control of Central Asia is referred to as the Great Game.",
  "1814"=> "Anglo-Nepalese War between Nepal (Gurkha Empire) and British Empire.",
  "1815"=> "The Congress of Vienna redraws the European map. The Concert of Europe attempts to preserve this settlement, but it fails to stem the tide of liberalism and nationalism that sweeps over the continent.",
  "1815"=> "Napoleon escapes exile and begins the Hundred Days before finally being defeated at the Battle of Waterloo and exiled to St Helena.",
  "1815"=> "Jane Austen publishes Emma in December.",
  "1816"=> "Year Without a Summer=> Unusually cold conditions wreak havoc throughout the Northern Hemisphere, likely influenced by the 1815 explosion of Mount Tambora.",
  "1816"=> "Independence of Argentina.",
  "1816"=> "Shaka's Zulu Kingdom becomes the largest in Southern Africa.",
  "1817"=> "Principality of Serbia becomes suzerain from the Ottoman Empire. Officially independent in 1867.",
  "1817"=> "First Seminole War begins in Florida.",
  "1817"=> "Russia commences its conquest of the Caucasus.",
  "1818"=> "Mary Shelley publishes Frankenstein.",
  "1818"=> "Independence of Chile.",
  "1819"=> "The composition of John Keats's 1819 odes.",
  "1819"=> "Peterloo massacre in England.",
  "1819"=> "The modern city of Singapore is established by the British East India Company.",
  "1819"=> "Théodore Géricault paints his masterpiece The Raft of the Medusa, and exhibits it in the French Salon of 1819 at the Louvre.",
  "1816"=> "Shaka rises to power over the Zulu Kingdom. Zulu expansion was a major factor of the Mfecane (“Crushing”) that depopulated large areas of southern Africa",
  "1820"=> "Missouri Compromise.",
  "1820"=> "Regency period ends in the United Kingdom.",
  "1820"=> "Discovery of Antarctica.",
  "1820"=> "Liberia founded by the American Colonization Society for freed American slaves.",
  "1820"=> "Dissolution of the Maratha Empire.",
  "1820"=> "At least 5000 Mexicans die in Apache raids, and 100 settlements are destroyed.[11]",
  "1821"=> "Mexico gains independence from Spain with the Treaty of Córdoba.",
  "1821"=> "Peru declares its independence from Spain.",
  "1821"=> "Navarino Massacre.",
  "1822"=> "First Mexican Empire, as Mexico's first post-independent government, ruled by Emperor Agustín I of Mexico.",
  "1821"=> "Greece becomes the first country to break away from the Ottoman Empire after the Greek War of Independence.",
  "1822"=> "Prince Pedro of Brazil proclaimed the Brazilian independence on September 7. On December 1, he was crowned as Emperor Dom Pedro I of Brazil.",
  "1823"=> "The British Empire annexed Burma (now also called Myanmar) after three Anglo-Burmese Wars.",
  "1823"=> "Monroe Doctrine declared by US President James Monroe.",
  "1824"=> "Premiere of Beethoven's Ninth Symphony.",
  "1825"=> "Erie Canal opened connecting the Great Lakes to the Atlantic Ocean.",
  "1825"=> "First isolation of aluminum.",
  "1825"=> "Independence of Bolivia.",
  "1825"=> "The Stockton and Darlington Railway, the first public railway in the world, is opened.",
  "1825"=> "The Decembrist revolt.",
  "1825"=> "The Cisplatine War results in the independence of Uruguay.",
  "1825"=> "Java War. (to 1830)",
  "1826"=> "Samuel Morey patents the internal combustion engine.",
  "1826"=> "After the final Russo-Persian War, the Persian Empire took back territory lost to Russia from the previous war.",
  "1827"=> "Death of William Blake, Ludwig van Beethoven",
  "1828"=> "Black War in Tasmania leads to the near extinction of the Tasmanian aborigines",
  "1829"=> "Johann Wolfgang von Goethe's Faust premieres.",
  "1829"=> "First electric motor built.",
  "1829"=> "Sir Robert Peel founds the Metropolitan Police Service, the first modern police force.",
  "1900"=> "1830=> The Church of Jesus Christ of Latter Day Saints is established on April 6, 1830.",
  "1830"=> "July Revolution in France.",
  "1830"=> "The Belgian Revolution in the United Kingdom of the Netherlands led to the creation of Belgium.",
  "1830"=> "Greater Colombia dissolved and the nations of Colombia (including modern-day Panama), Ecuador, and Venezuela took its place.",
  "1830"=> "November Uprising in Poland against Russia.",
  "1830"=> "End of the Diponegoro war. The whole area of Yogyakarta and Surakarta Manca nagara Dutch seized.",
  "1831"=> "France invades and occupies Algeria.",
  "1831"=> "The Belgian constitution is ratified and Leopold I is crowned as first 'King of the Belgians'.",
  "1831"=> "Great Bosnian uprising against Ottoman rule occurs.",
  "1831"=> "Charles Darwin's journey on the HMS Beagle.",
  "1831"=> "November Uprising ends with crushing defeat for Poland in the Battle of Warsaw.",
  "1831"=> "Egyptian War.",
  "1831"=> "Second phase of Padri War. (to 1838)",
  "1832"=> "The British Parliament passes the Great Reform Act.",
  "1833"=> "Slavery Abolition Act bans slavery throughout the British Empire.",
  "1833"=> "Carlist Wars in Spain.",
  "1834"=> "The German Customs Union is formed.",
  "1834"=> "Spanish Inquisition officially ends.",
  "1834"=> "Britain amends the Poor Law demanding that any paupers requesting assistance must go to a workhouse.",
  "1834"=> "Imam Shamil's rebellion in Russian-occupied Caucasus.",
  "1835"=> "The Texas Revolution in Mexico resulted in the short-lived Republic of Texas.",
  "1836"=> "Battle of the Alamo ends with defeat for Texan separatists.",
  "1836"=> "Battle of San Jacinto leads to the capture of General Santa Anna.",
  "1836"=> "Samuel Colt popularizes the revolver and sets up a firearms company to manufacture his invention of the Colt Paterson revolver a six bullets firearm shot one by one without reloading manually.",
  "1837"=> "Telegraphy patented.",
  "1837"=> "Charles Dickens publishes Oliver Twist.",
  "1837"=> "Death of Alexander Pushkin.",
  "1837"=> "Rebellions of 1837 in Canada.",
  "1837"=> "Queen Victoria's reign is considered the apex of the British Empire and is referred to as the Victorian era.",
  "1838"=> "By this time, 46,000 Native Americans have been forcibly relocated in the Trail of Tears.",
  "1838"=> "Civil war in the Federal Republic of Central America led to the foundings of Guatemala, El Salvador, Honduras, Nicaragua, and Costa Rica.",
  "1839"=> "Kingdom of Belgium declared.",
  "1839"=> "Uruguayan Civil War.",
  "1839"=> "After the First and Second Opium Wars, France, the United Kingdom, the United States and Russia gain many trade and associated concessions from China resulting in the start of the decline of the Qing dynasty.",
  "1839"=> "Anglo-Afghan Wars lead to stalemate and the establishment of the Durand line",
  "1900"=> "1840=> New Zealand is founded, as the Treaty of Waitangi is signed by the Māori and British.",
  "1840"=> "Upper and Lower Canada are merged into the Province of Canada.",
  "1842"=> "Treaty of Nanking cedes Hong Kong to the British.",
  "1842"=> "Anaesthesia used for the first time.",
  "1843"=> "The first wagon train sets out from Missouri.",
  "1843"=> "Short stories A Christmas Carol and The Tell-Tale Heart published.",
  "1844"=> "Persian Prophet the Báb announces his revelation on May 23, founding Bábísm. He announced to the world of the coming of 'He whom God shall make manifest'. He is considered the forerunner of Bahá'u'lláh, the founder of the Bahá'í Faith.",
  "1844"=> "First publicly funded telegraph line in the world—between Baltimore and Washington—sends demonstration message on May 24, ushering in the age of the telegraph. This message read 'What hath God wrought?'' (Bible, Numbers 23=>23)",
  "1844"=> "Millerite movement awaits the Second Advent of Jesus Christ on October 22. Christ's non-appearance becomes known as the Great Disappointment.",
  "1844"=> "The Great Auk is rendered extinct.",
  "1844"=> "Dominican War of Independence from Haiti.",
  "1845"=> "Unification of the Kingdom of Tonga under Tāufaʻāhau (King George Tupou I).",
  "1845"=> "First Anglo-Sikh War.",
  "1845"=> "The New Zealand Land Wars.",
  "1845"=> "The Irish Potato Famine leads to the Irish diaspora.",
  "1846"=> "The Mexican-American War leads to Mexico's cession of much of the modern-day Southwestern United States.",
  "1846"=> "Mormon migration to Utah.",
  "1847"=> "The Brontë sisters publish Jane Eyre, Wuthering Heights and Agnes Grey.",
  "1847"=> "The Caste War of Yucatán.",
  "1848"=> "Second Anglo-Sikh War",
  "1848"=> "The Communist Manifesto published.",
  "1848"=> "Revolutions of 1848 in Europe.",
  "1848"=> "Seneca Falls Convention is an early and influential women's rights convention in the United States and leads to the battle for women's suffrage.",
  "1848"=> "California Gold Rush.",
  "1848"=> "William Holman Hunt, John Everett Millais and Dante Gabriel Rossetti found the Pre-Raphaelite Brotherhood.",
  "1849"=> "The first boatloads of gold prospectors arrive in California, giving them the nickname 49ers.",
  "1849"=> "The safety pin and the gas mask are invented.",
  "1849"=> "Earliest recorded air raid, as Austria employs 200 balloons to deliver ordnance against Venice.",
  "1900"=> "1850=> The Little Ice Age ends around this time.",
  "1850"=> "Taiping Rebellion is the bloodiest conflict of the century, leading to the deaths of 20 million people.",
  "1851"=> "The Great Exhibition in London was the world's first international Expo or World Fair.",
  "1851"=> "Louis Napoleon assumes power in France in a coup.",
  "1851"=> "The Platine War ends and the Empire of Brazil has the hegemony over South America.",
  "1851"=> "Victorian gold rush in Australia",
  "1852"=> "Frederick Douglass delivers his speech 'The Meaning of July Fourth for the Negro' in Rochester, New York.",
  "1853"=> "United States Commodore Matthew C. Perry threatens the Japanese capital Edo with gunships, demanding that they agree to open trade.",
  "1853"=> "Crimean War between France, the United Kingdom, the Ottoman Empire and Russia",
  "1854"=> "Battle of Balaclava and the Charge of the Light Brigade.",
  "1854"=> "The Convention of Kanagawa formally ends Japan's policy of isolation.",
  "1854"=> "Siege of Sevastapol; city falls to British forces.",
  "1855"=> "Bessemer process enables steel to be mass-produced.",
  "1855"=> "Walt Whitman publishes the first edition of Leaves of Grass.",
  "1856"=> "World's first oil refinery in Romania",
  "1856"=> "Neanderthal man first identified. Age still unknown.",
  "1857"=> "Indian Rebellion of 1857. The British Empire assumes control of India from the East India Company.",
  "1858"=> "Invention of the phonautograph, the first true device for recording sound.",
  "1859"=> "Charles Darwin publishes On the Origin of Species.",
  "1859"=> "Suez Canal is constructed.",
  "1860"=> "Giuseppe Garibaldi launches the Expedition of the Thousand.",
  "1860"=> "The Pony Express started.",
  "1861"=> "American Civil War between the Union and seceding Confederacy.",
  "1861"=> "Russia abolishes serfdom.",
  "1861"=> "French intervention in Mexico and the creation of the Second Mexican Empire, ruled by Maximilian I of Mexico and his consort Carlota of Mexico.",
  "1862"=> "The Pony Express ended.",
  "1862"=> "French gain first foothold in Southeast Asia.",
  "1862"=> "Muslim Rebellion in northwest China.",
  "1863"=> "Bahá'u'lláh declares his station as 'He whom God shall make manifest'. This date is celebrated in the Bahá'í Faith as The Festival of Ridván.",
  "1863"=> "Formation of the International Red Cross is followed by the adoption of the First Geneva Convention in 1864.",
  "1863"=> "First section of the London Underground opens.",
  "1863"=> "France annexes Cambodia.",
  "1863"=> "Édouard Manet exhibits his painting Le déjeuner sur l'herbe, sparking public outrage.",
  "1864"=> "Circassian Genocide.(21 May 1864)",
  "1863"=> "Polish uprising against the Russian Empire.",
  "1864"=> "The Chincha Islands War was an attempt by Spain to regain its South American colonies.",
  "1864"=> "The Paraguayan War ends Paraguayan ambitions for expansion and destroys much of the Paraguayan population.",
  "1864"=> "June, The first railway track in Indonesia was laid between Semarang and Tanggung, Central Java by the Dutch colonial government.[14]",
  "1865"=> "Reconstruction in the United States; Slavery is banned in the United States by the Thirteenth Amendment to the United States Constitution.",
  "1865"=> "Robert E. Lee surrenders the Army of Northern Virginia (26,765 troops) to Ulysses S. Grant at Appomattox Courthouse, Virginia, effectively ending the American Civil War.",
  "1865"=> "United States President Abraham Lincoln is assassinated by actor and Confederate sympathizer John Wilkes Booth, while attending a performance at Ford's Theater, Washington, D.C.. He dies approximately nine hours after being shot on April 15, 1865.",
  "1865"=> "Gregor Mendel formulates his laws of inheritance.",
  "1865"=> "Lewis Carroll publishes Alice's Adventures in Wonderland.",
  "1866"=> "Successful transatlantic telegraph cable follows an earlier attempt in 1858.",
  "1866"=> "Austro-Prussian War results in the dissolution of the German Confederation and the creation of the North German Confederation and the Austrian-Hungarian Dual Monarchy.",
  "1866"=> "Famine in Finland.",
  "1866"=> "After the Meiji Restoration, Japan embarks on a program of rapid modernization.",
  "1867"=> "The United States purchases Alaska from Russia.",
  "1867"=> "Canadian Confederation formed.",
  "1867"=> "The Principality of Serbia passes a Constitution which defines its independence from the Ottoman Empire. International recognition followed in 1878.",
  "1867"=> "The Luxembourg Crisis=> diplomatic confrontation between France and Prussia on the status of Luxembourg and the towns fortifications are torn down.",
  "1868"=> "The Expatriation Act of 1868 is approved by the U.S. Congress, one of the early blows which would eventually lead to the death of the common law doctrine of perpetual allegiance",
  "1868"=> "The Fourteenth Amendment to the United States Constitution is approved.",
  "1868"=> "Cro-Magnon man first identified.",
  "1868"=> "Ten Years' War between Cuba and Spain.",
  "1868"=> "The Batavian Museum (today National Museum of Indonesia) was officially opened by Dutch East Indies government.",
  "1869"=> "Leo Tolstoy publishes War and Peace.",
  "1869"=> "First Transcontinental Railroad completed in United States on May 10.",
  "1869"=> "Dmitri Mendeleev created the Periodic table.",
  "1869"=> "The Suez Canal opens linking the Mediterranean to the Red Sea.",
  "1900"=> "1870=> The Franco-Prussian War results in the unifications of Germany and Italy, the collapse of the Second French Empire and the emergence of a New Imperialism.",
  "1870"=> "Official dismantling of the Cultivation System and beginning of a 'Liberal Policy' of deregulated exploitation of the Netherlands East Indies.[15]",
  "1871"=> "In Germany, Otto von Bismarck attacks the privileges of the Catholic Church in the Kulturkampf ('Culture War')",
  "1871"=> "Famine in Persia is believed to have caused the death of 2 million.",
  "1871"=> "Second Industrial Revolution",
  "1870"=> "Long Depression in Western Europe and North America.",
  "1871"=> "The Paris Commune briefly rules the French capital.",
  "1871"=> "The feudal system is dismantled in Japan.",
  "1871"=> "Henry Morton Stanley meets Dr. David Livingstone near Lake Tanganyika.",
  "1872"=> "Yellowstone National Park, the first national park, is created.",
  "1872"=> "The first recognised international soccer match, between England and Scotland, is played.",
  "1873"=> "The Panic of 1873 starts the 'Long Depression'.",
  "1873"=> "Maxwell's A Treatise on Electricity and Magnetism published.",
  "1873"=> "The samurai class is abolished in Japan.",
  "1873"=> "Blue jeans and barbed wire are invented.",
  "1873"=> "The beginning of the bloody Aceh War for Dutch occupation of the province.[15]",
  "1874"=> "The Société Anonyme Coopérative des Artistes Peintres, Sculpteurs, and Graveurs, better known as the Impressionists, organize and present their first public group exhibition at the Paris studio of the photographer Nadar.",
  "1874"=> "The Home Rule Movement is established in Ireland.",
  "1874"=> "The British East India Company is dissolved.",
  "1874"=> "First Republic in Spain.",
  "1875"=> "HMS Challenger surveys the deepest point in the Earth's oceans, the Challenger Deep",
  "1875"=> "26 million Indians perish in India due to famine.",
  "1876"=> "Bulgarians instigate the April Uprising against Ottoman rule.",
  "1876"=> "Richard Wagner's Ring Cycle is first performed in its entirety.",
  "1876"=> "Queen Victoria becomes Empress of India.",
  "1876"=> "Battle of the Little Bighorn leads to the death of General Custer and victory for the alliance of Lakota, Cheyenne and Arapaho",
  "1876"=> "13 million Chinese die of famine in northern China.",
  "1876"=> "The massive expansion in population, territory, industry and wealth in the United States is referred to as the Gilded Age.",
  "1877"=> "Great Railroad Strike in the United States may have been the world's first nationwide labor strike.",
  "1877"=> "Crazy Horse surrenders and is later killed",
  "1877"=> "Asaph Hall discovers the moons of Mars",
  "1877"=> "Thomas Edison invents the phonograph",
  "1877"=> "Following the Russo-Turkish War, the Treaty of Berlin recognizes formal independence of the Principality of Serbia, Montenegro and Romania. Bulgaria becomes autonomous.",
  "1878"=> "First commercial telephone exchange in New Haven, Connecticut.",
  "1879"=> "Anglo-Zulu War in South Africa.",
  "1879"=> "Thomas Edison tests his first light bulb.",
  "1879"=> "Little War against Spanish rule in Cuba leads to rebel defeat.",
  "1879"=> "Chile battles with Peru and Bolivia over Andean territory in the War of the Pacific.",
  "1879"=> "Belgium is engulfed in a political crisis, dubbed the First School War, over the role of religion in state education.",
  "1879"=> "21 April, Kartini was born in Jepara, today the date is commemorated as women's emancipation day in Indonesia.",
  "1900"=> "The First Boer War.",
  "1881"=> "Tsar Alexander II is assassinated.",
  "1881"=> "Wave of pogroms begins in the Russian Empire.",
  "1881"=> "Gunfight at the O.K. Corral. Sitting Bull surrenders.",
  "1881"=> "First electrical power plant and grid in Godalming, Britain.",
  "1881"=> "The Jules Ferry laws are passed in France establishing free, secular education.",
  "1881"=> "The Mahdist War in Sudan.",
  "1882"=> "The British invasion and subsequent occupation of Egypt",
  "1883"=> "Krakatoa volcano explosion, one of the largest in modern history.",
  "1883"=> "The quagga is rendered extinct.",
  "1883"=> "Robert Louis Stevenson's Treasure Island is published.",
  "1884"=> "Siege of Khartoum.",
  "1884"=> "Germany gains control of Cameroon.",
  "1884"=> "Mark Twain publishes The Adventures of Huckleberry Finn.",
  "1884"=> "The Berlin Conference signals the start of the European 'scramble for Africa'. Attending nations also agree to ban trade in slaves.",
  "1884"=> "The Sino-French War led to the formation of French Indochina.",
  "1885"=> "Louis Pasteur creates the first successful vaccine against rabies for a young boy who had been bitten 14 times by a rabid dog.",
  "1885"=> "King Leopold II of Belgium establishes the Congo Free State as a personal fiefdom.",
  "1885"=> "Britain establishes a protectorate over Bechuanaland (modern Botswana).",
  "1885"=> "Singer begins production of the 'Vibrating Shuttle'. which would become the most popular model of sewing machine.",
  "1886"=> "'The Strange Case of Dr. Jekyll and Mr. Hyde' by Robert Louis Stevenson is published.",
  "1886"=> "Burma is presented to Queen Victoria as a birthday gift.",
  "1886"=> "Karl Benz sells the first commercial automobile.",
  "1886"=> "Construction of the Statue of Liberty; Coca-Cola is developed.",
  "1886"=> "Russian-Circassian War ended with the defeat and the exile of many Circassians. Imam Shamil defeated.",
  "1887"=> "The British Empire takes over Balochistan.",
  "1887"=> "Sir Arthur Conan Doyle publishes his first Sherlock Holmes story, A Study in Scarlet.",
  "1888"=> "Louis Le Prince records the Roundhay Garden Scene, the earliest surviving film.",
  "1888"=> "Jack the Ripper murders occur in Whitechapel, London.",
  "1888"=> "Slavery banned in Brazil.",
  "1888"=> "Founding of the shipping line Koninklijke Paketvaart-Maatschappij (KPM) that supported the unification and development of the colonial economy.[15]",
  "1889"=> "The Mayerling Incident=> Crown Prince Rudolf of Austria and Baroness Mary Vetsera are found dead in an apparent murder-suicide.",
  "1889"=> "Eiffel Tower is inaugurated in Paris.",
  "1889"=> "Mirza Ghulam Ahmad establishes the Ahmadiyya Muslim Community, a reform sect of Islam.",
  "1889"=> "End of the Brazilian Empire and the beginning of the Brazilian Republic.",
  "1889"=> "Vincent van Gogh paints Starry Night.",
  "1889"=> "Aspirin patented.",
  "1889"=> "Moulin Rouge opens in Paris.",
  "1900"=> "1890=> The Wounded Knee Massacre was the last battle in the American Indian Wars. This event represents the end of the American Old West.",
  "1890"=> "Italy annexes Eritrea.",
  "1890"=> "Independence of Luxembourg.",
  "1890"=> "Death of Vincent van Gogh.",
  "1891"=> "Mirza Ghulam Ahmad, founder of the Ahmadiyya movement, claims to be Promised Messiah and Imam Mahdi",
  "1890"=> "The cardboard box is invented.",
  "1891"=> "1891 Chilean Civil War.",
  "1892"=> "Basketball is invented.",
  "1892"=> "The World's Columbian Exposition was held in Chicago celebrating the 400th anniversary of Christopher Columbus's arrival in the New World.",
  "1892"=> "Fingerprinting is officially adopted for the first time.",
  "1892"=> "Tchaikovsky's Nutcracker Suite premières in St Petersberg.",
  "1893"=> "US forces overthrow the government of Hawaii.",
  "1893"=> "The Internal Macedonian Revolutionary Organisation is formed.",
  "1893"=> "New Zealand becomes the first country to enact women's suffrage.",
  "1893"=> "The Coremans-de Vriendt law is passed in Belgium, creating legal equality for French and Dutch languages.",
  "1894"=> "First commercial film release by Jean Aimé Le Roy.[citation needed]",
  "1894"=> "First gramophone record.",
  "1894"=> "France and the Russian Empire form a military alliance.",
  "1894"=> "After the First Sino-Japanese War, China cedes Taiwan to Japan and grants Japan a free hand in Korea.",
  "1894"=> "Lombok War The Dutch looted and destroyed the Cakranegara palace of Mataram. J. L. A. Brandes, a Dutch philologist discovered and secured Nagarakretagama manuscript in Lombok royal library.",
  "1895"=> "Volleyball is invented.",
  "1895"=> "Trial of Oscar Wilde and premiere of his play The Importance of Being Earnest.",
  "1895"=> "French troops capture Antananarivo in Madagascar.",
  "1895"=> "Wilhelm Röntgen identifies x-rays.",
  "1894"=> "Dreyfuss Affair in France.",
  "1895"=> "Abyssinia defeats Italy in the First Italo War.",
  "1895"=> "Cuban War for Independence results in Cuban independence from Spain.",
  "1896"=> "Olympic Games revived in Athens.",
  "1896"=> "Philippine Revolution ends declaring Philippines free from Spanish rule.",
  "1896"=> "Ethiopia defeated Italy at the Battle of Adwa.",
  "1896"=> "Klondike Gold Rush in Canada.",
  "1896"=> "Henri Becquerel discovers radioactivity; J. J. Thomson identifies the electron, though not by name.",
  "1897"=> "Gojong, or Emperor Gwangmu, proclaims the short-lived Korean Empire=> lasts until 1910.",
  "1897"=> "Benin Expedition of 1897 loots and burns Benin.",
  "1897"=> "Greco-Turkish War.",
  "1897"=> "Bram Stoker writes Dracula.",
  "1898"=> "The United States gains control of Cuba, Puerto Rico, and the Philippines after the Spanish-American War.",
  "1898"=> "Empress Dowager Cixi of China engineers a coup d'état, marking the end of the Hundred Days' Reform; the Guangxu Emperor is arrested.",
  "1898"=> "H. G. Wells publishes The War of the Worlds",
  "1898"=> "The Boxer Rebellion in China is suppressed by an Eight-Nation Alliance.",
  "1898"=> "The Thousand Days' War in Colombia breaks out between the 'Liberales' and 'Conservadores', culminating with the loss of Panama in 1903.",
  "1898"=> "General van Heutz becomes chief of staff of Aceh campaign. Wilhelmina becomes queen of the Netherlands.[15]",
  "1899"=> "Second Boer War begins (-1902); Philippine-American War begins (-1913).",
  "1899"=> "Indian famine kills over 1 million people.",
  "1900"=> "Hawaii becomes an official U.S. territory. Galveston Hurricane kills 8000 people.",
  "1901" => "Australian colonies unified under single government. Boxer Rebellion ends. Edward VII becomes King of the United Kingdom and the British Dominions and Emperor of India upon the death of Queen Victoria. Platt Amendment limits the autonomy of Cuba in exchange for withdrawal of American troops. Emily Hobhouse reports on the genocide in the 45 British concentration camps for Boer women and children in South Africa. Guglielmo Marconi receives the first trans-Atlantic radio signal.",
  "1902" => "Second Boer War ends. Philippine–American War ends. Cuba gains independence from the United States. Unification of Saudi Arabia begins. Venezuela Crisis, in which Britain, Germany and Italy sustain a naval blockade on Venezuela in order to enforce collection of outstanding financial claims.",
  "1903" => "First controlled heavier-than-air flight of the Wright Brothers. Herero and Namaqua Genocide, the first genocide of the 20th century, begins in German South-West Africa. In Russia the Bolsheviks and the Mensheviks form from the breakup of the Russian Social Democratic Labor Party. Pius X becomes Pope. The teddy bear is invented. Independence of Panama, the Hay–Bunau-Varilla Treaty is signed by the United States and Panama. The Ottoman Empire and the German Empire sign an agreement to build the Constantinople-Baghdad Railway.",
  "1904" => "Entente cordiale signed between Britain and France. A Japanese surprise attack on Port Arthur (Lushun) starts the Russo-Japanese War. Trans-Siberian railway is completed. Construction of the Panama Canal begins. Roger Casement publishes his account of Belgian atrocities in the Congo Free State. End of British expedition to Tibet.",
  "1905" => "Russo-Japanese War ends. Revolution of 1905 in Russia. Persian Constitutional Revolution begins. Trans-Siberian Railway opened. Albert Einstein's formulation of relativity. Schlieffen Plan proposed. The British Indian Province of Bengal, was partitioned by the Viceroy of India, Lord Curzon. First Moroccan Crisis. The Norwegian Parliament declares the union with Sweden dissolved, and Norway achieves full independence.",
  "1906" => "Earthquakes in San Francisco, California (death toll: 3000) and Valparaíso, Chile (death toll: 20,000) occur. Dreyfus Affair ends. Stolypin reform in Russia creates a new class of affluent kulaks. Brazilian inventor Alberto Santos-Dumont takes off and flies his 14-bis to a crowd in Paris. The Muslim League is formed by Nawab Salimullah Khan of Dacca. The US began the Second Occupation of Cuba.",
  "1907" => "Herero and Namaqua Genocide ends. A peasants' revolt in Romania kills roughly 11,000. The Indian National Congress splits into two factions at its Surat session, presided by Rash Behari Bose. Persian Constitutional Revolution ends with the establishment of a parliament. Japan–Korea Treaty of 1907. The Anglo-Russian Entente bring a pause in The Great Game in Central Asia. Elections to the new Parliament of Finland are the first in the world with woman candidates, as well as the first elections in Europe where universal suffrage is applied.",
  "1908" => "First commercial radio transmissions. The Ford Motor Company invents the Model T. First commercial Middle-Eastern oilfield established, at Masjed Soleyman in southwest Persia. The Tunguska impact devastates thousands of square kilometres of Siberia. Young Turk Revolution in the Ottoman Empire. Independence of Bulgaria. Austro-Hungary annexes Bosnia-Herzegovina, triggering the Bosnian Crisis. Pu Yi, the last Emperor of China, assumes the throne. 1908 Messina earthquake kills over 70,000 people. Start of publication of Robert Baden-Powell's Scouting for Boys in London.",
  "1909" => "United States troops leave Cuba. Bosnian crisis ends with Austro-Hungary's annexation of Bosnia and Herzegovina. Robert E. Peary claims to have reached the North Pole though the claim is subsequently heavily contested. Anglo-Siamese Treaty of 1909. Ottoman countercoup fails in the Ottoman Empire. A revolution forces Mohammad Ali Shah, Persian Shah of the Qajar dynasty to abdicate in favor of his son Ahmad Shah Qajar. Japan and China sign the Jiandao/Gando Treaty",
  "1910" => "Beginning of the Mexican Revolution. George V becomes King of the United Kingdom and the British Dominions and Emperor of India. Union of South Africa created. 5 October 1910 revolution in Portugal and proclamation of the First Portuguese Republic. Imperial Japan annexes Korea. Boy Scouts of America is founded. Halley's Comet returns. Montenegro is proclaimed an independent kingdom. Albanian Revolt of 1910.",
  "1911" => "Xinhai Revolution in China overthrows the Qing Dynasty. Roald Amundsen first reaches the South Pole. New Delhi becomes the capital of British India. Ernest Rutherford identifies the atomic nucleus. The Italo-Turkish war leads to the capture of Libya by Italy. Eugene B. Ely lands on the deck of the USS Pennsylvania stationed in San Francisco harbor, marking the first time an aircraft lands on a ship. Agadir Crisis.",
  "1912" => "End of the Chinese Empire; Republic of China established. The African National Congress is founded. Morocco becomes a protectorate of France. Sinking of the RMS Titanic. First Balkan War begin. Woodrow Wilson is elected 28th President of the United States. Arizona becomes the last state to be admitted to the continental Union. United States occupation of Nicaragua begins. The Kuomintang, the Chinese nationalist party, is founded.",
  "1913" => "Niels Bohr formulates the first cohesive model of the atomic nucleus, and in the process paves the way to quantum mechanics. In the 1913 Ottoman coup d'état, Ismail Enver comes to power.Ford Motor Company introduces the first moving assembly line. La Decena Trágica. Yuan Shikai uses military force to dissolve China's parliament and rules as a dictator.Treaty of London. Second Balkan War and Treaty of Bucharest. The Federal Reserve System is created.",
  "1914" => "Gavrilo Princip assassinates Archduke Franz Ferdinand of Austria in Sarajevo, triggering the start of World War I. The United Kingdom establishes the Sultanate of Egypt as a protectorate. Panama Canal opens. Benedict XV becomes Pope. Martha, last known Passenger Pigeon, dies.",
  "1915" => "The RMS Lusitania is sunk. The United States occupation of Haiti begins. Armenian genocide in the Ottoman Empire. First use of poison gas at the Battle of Neuve Chapelle and Second Battle of Ypres.",
  "1916" => "Easter Rising in Ireland. The implementation of daylight saving time. Warlord Era begins in China. David Lloyd George becomes the Prime Minister of the United Kingdom. The Gallipoli Campaign fails. First use of tanks at the Battle of Flers-Courcelette. Battle of the Somme. Grigory Rasputin is assassinated by H.H. Prince Felix Youssoupov. The Pact is agreed upon by both the Congress and the Muslim League at the Indian city of Lucknow. Battle of Verdun. The Arab Revolt begins",
  "1917" => "Russian Revolution ends the Russian Empire; beginning of Russian Civil War. USA join the Allies for the last 17 months of World War I. Independence of Poland recognised. The first Pulitzer Prizes are awarded. October Revolution in Russia.",
  "1918" => "End of World War I. German Revolution begins. Abdication of Kaiser Wilhelm II. Spanish flu pandemic. Murder of Tsar Nicholas II and his family. Poland, Ukraine and Belarus are among a number of states to declare independence from Russia. Finnish Civil War. Mehmed VI becomes last Sultan of the Ottoman Empire and last Caliph. Partitioning of the Ottoman Empire begins. The Kingdom of Iceland and The State of Slovenes, Croats and Serbs are established. The British occupy Palestine. Mutawakkilite Kingdom of Yemen is founded. Azerbaijan Democratic Republic is declared. Armenian–Azerbaijani War begins.",
  "1919" => "Treaty of Versailles redraws European borders. German Revolution ends with the collapse of the German Empire and the establishment of the Weimar Republic. Victory for Estonia in the Estonian War of Independence. League of Nations founded in Paris. Polish-Soviet War begins. The Italian National Fascist Party is established by Benito Mussolini. Comintern established. Egyptian Revolution of 1919. Turkish War of Independence begins. The International Labor Organisation is established. Ernest Rutherford discovers the proton. First experimental evidence for the General theory of relativity obtained by Arthur Eddington.",
  "1920" => "Mexican Revolution ends. Greece restores its monarchy after a referendum. Turkish–Armenian War is fought, and ends with victory for Turkey. Red Army invasion of Azerbaijan and Armenia ends the Armenian–Azerbaijani War and concludes with their incorporation into the Soviet Union.Mohandas Gandhi launches Non-cooperation movement.",
  "1921" => "Adolf Hitler becomes Führer of the Nazi Party as hyperinflation in the Weimar Republic begins. Russia invades Georgia and incorporates it into the Soviet Union. End of Russian Civil War and Polish-Soviet War. Coup brings the Pahlavi dynasty to power in Iran.",
  "1922" => "Ottoman Sultanate abolished by the Turkish Grand National Assembly; Sultan Mehmed VI is deposed. Irish Free State is established, while the Province of Northern Ireland is created within The United Kingdom. The Irish Civil War begins. The Italian reconquest of Libya begins. The union of Costa Rica, Guatemala, Honduras and El Salvador is dissolved. Egypt gains independence from the United Kingdom, though British forces still occupy the Suez Canal. March on Rome brings Benito Mussolini to power in Italy. Howard Carter discovers Tutankhamen's tomb. Gabriel Narutowicz, President of Poland is assassinated.",
  "1923" => "Hyperinflation in the Weimar Republic ends with the introduction of the Rentenmark. Time Magazine is first published. Irish Civil War ends. The Beer Hall Putsch, an attempt to overthrow the Weimar Republic, ends in failure and brief imprisonment for Adolf Hitler but brings the Nazi Party to national attention. A military coup ousts and kills Bulgarian Prime Minister Aleksandar Stamboliyski. The Great Kantō earthquake kills at least 105,000 people in Japan. Ankara replaces Istanbul as the capital of Turkey, while Kemal Atatürk becomes the first President of the newly established Republic of Turkey. The Walt Disney Company is founded.",
  "1924" => "Death of Vladimir Lenin triggers power struggle between Leon Trotsky and Joseph Stalin. The Caliphate is abolished by Kamal Atatürk. The U.S. Federal Bureau of Investigation founded under J. Edgar Hoover. The August Uprising in Georgia against Soviet rule. George Gershwin composes Rhapsody In Blue. U.S. Immigration Act of 1924 significantly restricts immigration from Asia, the Middle East, and Southern Europe.",
  "1925" => "Benito Mussolini gains dictatorial powers in Italy. Mein Kampf is published. First televisual image created by John Logie Baird. Locarno Treaties are signed. Serum run to Nome.",
  "1926" => "Hirohito becomes Emperor of Japan. Coups in Greece, Poland and Portugal install new dictatorships.",
  "1928" => "Discovery of penicillin by Alexander Fleming. Warlord Era ends in China. Malta becomes a British Dominion. King Zog I is crowned in Albania. The Kellogg-Briand Pact is signed in Paris. The International Red Cross and Red Crescent Movement is established. Mickey Mouse is created at the Walt Disney Studio. Hassan al-Banna founds the Muslim Brotherhood.",
  "1929" => "Wall Street crash of 1929 and the beginning of the Great Depression. Leon Trotsky is exiled First people sent to the gulag in the Soviet Union as Stalin assumes effective control. Pope Pius XI signs the Lateran Treaty with Italian leader Benito Mussolini. Vatican City is recognised as a sovereign state. The first Academy Awards are presented.",
  "1930" => "Aided by the Great Depression, the Nazi Party increases its share of the vote from 2.6% to 18.3%. Clyde Tombaugh discovers Pluto. Salt March by Mohandas Gandhi and the official start of civil disobedience in British India. Military coups replace governments in Peru and Brazil. Haile Selassie becomes king of Abyssinia. First FIFA World Cup hosted.",
  "1932" => "Franklin D. Roosevelt is elected President of the United States. Éamon de Valera becomes President of the Executive Council (prime minister) of the Irish Free State. The Nazi party becomes the largest single party in the German parliament. Military coup in Chile. BBC World Service starts broadcasting. The Neutron is discovered.",
  "1933" => "Adolf Hitler becomes Chancellor of Germany. New Deal begins in America. Japan and Germany announce they are going to leave the League of Nations. United States occupation of Nicaragua ends.",
  "1934" => "Dictatorships begin in Brazil and Bolivia. Mao Zedong begins the Long March. United States occupation of Haiti ends. United States grants more autonomy to the Philippines. Adolf Hitler instigates the Night of the Long Knives, which cements his power over both the Nazi Party and Germany. With the death of President Hindenburg, Hitler declares himself Fuhrer of Germany.",
  "1935" => "Second Italo-Abyssinian War concludes with the exile of Haile Selassie and the conquest of Abyssinia by Benito Mussolini. Persia becomes Iran. William Lyon Mackenzie King is elected Prime Minister of Canada. Enactment of the Nuremberg racial laws.",
  "1937" => "Japanese invasion of China, and the beginning of World War II in the Far East. Rape of Nanking. Neville Chamberlain becomes Prime Minister of the United Kingdom. The Irish Republican Army attempts to assassinate King George VI of the United Kingdom. Deaths of George Gershwin and Maurice Ravel. German zeppelin Hindenburg crashes in Lakehurst, New Jersey.",
  "1938" => "Anschluss unifies Germany and Austria. Munich agreement hands Czechoslovakia to Nazi Germany. Great Purge ends after nearly 700,000 executions. Kristallnacht in Germany, while Time Magazine declares Adolf Hitler as Man of the Year. DC Comics hero Superman has its first appearance.",
  "1939" => "End of Spanish Civil War; Francisco Franco becomes dictator of Spain. Molotov–Ribbentrop Pact between Germany and the Soviet Union. Nazi invasion of Poland triggers the beginning of World War II in Europe. Soviet invasion of Poland begins 16 days later. Palestinian revolt against the British ends. Pius XII becomes Pope.",
  "1940" => "Nazis invade France, the Netherlands, Denmark and Norway. Katyn massacre of Polish soldiers in USSR and the Soviet occupation of the Baltic states. Winter War between Soviet Union and Finland. Winston Churchill becomes Prime Minister of the United Kingdom. Battle of Britain, the first entirely aerial military campaign, becomes the first significant defeat for the Axis powers. The Blitz begins. Leon Trotsky is assassinated. Chechen insugency begins in Soviet Union.",
  "1941" => "Operation Reinhard commences the main phase of The Holocaust. Attack on Pearl Harbor, which leads to the USA joining World War II. Hitler commences the Nazi invasion of the Soviet Union. Siege of Tobruk in North Africa is the first major defeat for Hitler's land forces. Siege of Leningrad begins.",
  "1942" => "Battle of Midway. Battle of the Coral Sea. First and second Battles of El Alamein. Battle of Stalingrad and Guadalcanal Campaign begin. Internment of Japanese-American citizens in the US begins. Manhattan Project begins.",
  "1943" => "Battle of Stalingrad ends with over two million casualties and the retreat of the German Army. The failed Battle of Kursk becomes the last Nazi offensive on the Eastern Front. Warsaw Ghetto uprising fails. Tehran Conference been Franklin Roosevelt, Winston Churchill and Joseph Stalin agrees to launch Operation Overlord. Green Revolution begins.",
  "1944" => "D-Day. The Siege of Leningrad ends with Soviet victory after over a million deaths. Baltic states are annexed by the Soviet Union. Chechen insurgency ends with deportation of the entire Chechen population. First operational electronic computer, Colossus, comes online",
  "1945" => "Bombing of Dresden. Battle of Berlin. Yalta Conference. End of World War II in Europe. The Holocaust ends after ~12 million deaths, including 6 million Jews. Deaths of Franklin Delano Roosevelt, Adolf Hitler and Benito Mussolini. Creation of the atomic bomb, and the atomic bombings of Hiroshima and Nagasaki. End of World War II in Asia and beginning of the Occupation of Japan. Potsdam Conference divides Europe into Western and Soviet blocs. United Nations founded. Independence of Korea. Deaths of Anne Frank and Béla Bartók. Independence of Indonesia. Nuremberg trials begin.",
  "1946" => "Italy becomes a republic. French Fourth Republic established. Independence of Jordan. Nuremberg trials end. First Indochina War begins. First images taken of the Earth from space. Bhumibol Adulyadej becomes King of Thailand. Mustafa Barzani founds the Kurdistan Democratic Party. Treaty of Manila declares Philippines independent.",
  "1947" => "Independence of India and Pakistan and beginning of First Indo-Pakistani War. Invention of the first practical transistor. Breaking of the sound barrier. Harry Truman establishes the Truman Doctrine of containment of Communism. Creation of the U.S. Central Intelligence Agency.",
  "1948" => "United Nations establishes Israeli Independence and the formation of the official State of Israel. Arab-Israeli War. Berlin Blockade begins. Marshall Plan; founding of the OECD and the World Health Organization. Assassination of Mohandas Gandhi. The independence of Burma. Beginning of apartheid in South Africa. Division of North and South Korea. First Indo-Pakistani War ends. The Soviet Sever-2 expedition become the first party to indisputably set foot on the North Pole.",
  "1949" => "Creation of NATO. Berlin Blockade ends. Partition of Germany into the Soviet socialist German Democratic Republic and the NATO-backed Federal Republic of Germany. COMECON founded by USSR and the Eastern Bloc. Partition of Kashmir. Establishment of the People's Republic of China under Mao Zedong; The Republic of China relocates to Taiwan. Soviet Union tests atomic bomb.",
  "1950" => "Communist victory in the Landing Operation on Hainan Island and Wanshan Archipelago Campaign end the Chinese Civil War. Beginning of the Korean War. Lhamo Dondrub becomes the 14th Dalai Lama of Tibet.",
  "1951" => "Colombo Plan comes into effect. Treaty of San Francisco ends the Occupation of Japan and formally concludes hostilities between Japan and the US.",
  "1952" => "European Defence Community formed. Egyptian Revolution under Gamal Abdel Nasser overthrows King Farouk and ends British occupation. Queen Elizabeth II becomes Monarch of the Commonwealth realms. Bonn–Paris conventions end allied occupation of West Germany. Slansky Trial in Czechoslovakia. Detonation of the hydrogen bomb. First scheduled flight by commercial jet. Development of the first effective polio vaccine by Jonas Salk. Mau Mau Uprising begins in Kenya.",
  "1953" => "Independence of Cambodia. Discovery of DNA. First ascent of Mount Everest. Mohammed Mossadeq deposed in Iran. End of the Korean War. Death of Joseph Stalin; East German Uprising leads to the arrest and execution of Lavrentiy Beria; power struggle begins between Georgy Malenkov and Nikita Khrushchev. Elvis Presley's musical career is launched.",
  "1954" => "Paris Treaty establishes Western European Union, Supreme Court of the United States decides Brown v. Board of Education, ordering an end to racial segregation in public schools. Rock Around the Clock by Bill Haley and His Comets, brings rock and roll to the American mainstream. The Soviet Union generates first electricity by nuclear power. First Indochina War ends. Algerian War begins.",
  "1955" => "Nikita Khrushchev assumes control of the Soviet Union. Signing of the Warsaw Pact. First Sudanese Civil War begins. Antimatter first produced. Formation of the Central Treaty Organization.",
  "1956" => "Independence of Sudan and Tunisia and full independence of Pakistan. French Fifth Republic established. The Hungarian Uprising crushed by Soviet troops. Nasser's nationalisation of the Suez Canal triggers the Suez crisis. Brasilia constructed.",
  "1957" => "Launch of Sputnik 1 and the beginning of the Space Age. Independence of Ghana. Treaty of Rome, which would eventually lead to the European Union. Harold Macmillan become British Prime Minister. First prescription of the combined oral contraceptive pill.",
  "1958" => "Great Chinese Famine begins in China. NASA, the U.S. Federal Aviation Authority and Campaign for Nuclear Disarmament (CND) founded. CND's symbol, the peace sign, is first used. Invention of the optical disc and the cassette tape.",
  "1959" => "Cuban Revolution. Independence of Cyprus and Singapore. Admission of Alaska and Hawaii into the United States. The Dalai Lama is exiled from Tibet. First documented AIDS cases. Beginning of the Vietnam War. First images of the far side of the Moon. Richie Valens, Buddy Holly and The Big Bopper die in a plane crash. By this time, the gulag has been effectively disbanded, after over a million recorded deaths. World population reaches 3 billion.",
  "1960" => "European Free Trade Association formed. 1960 U-2 incident sparks deterioration in relations between superpowers. Year of Africa: Independence of 17 African nations. Assassination of Patrice Lumumba begins Congo Crisis begins. Sharpeville Massacre in South Africa. Mau Mau Uprising ends. First manned descent to the deepest point on Earth, the Mariana Trench. Construction of the first laser. The Beatles form in Liverpool. Muhammad Ali wins gold in Rome.",
  "1961" => "Great Leap Forward ends in China after the deaths of roughly 20 million people. Construction of the Berlin Wall. First human spaceflight. Congo Crisis: Assassination of Prime Minister Patrice Lumumba. UN Secretary General Dag Hammarskjöld dies in a plane crash.",
  "1962" => "Cuban missile crisis. Algerian war ends with the independence of Algeria. The Beatles' first record and the beginnings of the British Invasion. Death of Marilyn Monroe. Indonesia–Malaysia confrontation begins. A coup ends the Mutawakkilite Kingdom of Yemen and establishes the Yemen Arab Republic. North Yemen Civil War begins. Sino-Indian War. Second Vatican Council is opened by Pope John XXIII.",
  "1964" => "Leonid Brezhnev ousts Khrushchev and assumes power in the Soviet Union. Independence of Malta, Malawi and Tanzania. Civil Rights Act abolishes segregation in the USA. Colombian armed conflict begins. Rhodesian Bush War begins. First close-up images of Mars",
  "1965" => "Deaths of Winston Churchill and Malcolm X. Congo Crisis ends; Joseph Mobutu becomes dictator of the Congo. Anti-Communist purge in Indonesia kills up to 500,000 people. Second Indo-Pakistani War. Second Vatican Council is closed by Pope Paul VI.",
  "1966" => "Indonesia–Malaysia confrontation ends. China's Cultural Revolution begins. Independence of Lesotho, Botswana and Barbados.",
  "1967" => "Summer of Love. Six Day War. Attempted secession of the Republic of Biafra from Nigeria triggers the Nigerian Civil War. ASEAN founded.",
  "1968" => "Assassinations of Martin Luther King, Jr. and Robert F. Kennedy during the Poor People's Campaign. Prague Spring crushed by Eastern Bloc military intervention. May 1968 protests in France. The Troubles begin in Northern Ireland. Tet Offensive occurs in South Vietnam.",
  "1969" => "Moon landings. Woodstock festival. Creation of ARPANET, the earliest incarnation of the Internet. Muammar Gaddafi overthrows King Idris of Libya in a Coup d'état and establishes the Libyan Arab Republic.",
  "1971" => "Black September in Jordan ends. Bangladesh Liberation War ends in independence of Bangladesh from Pakistan and precipitates Third Indo-Pakistani War. Internment begins in Northern Ireland. Invention of the microchip. Idi Amin seizes power in Uganda. Joseph Mobutu renames The Republic of the Congo Zaire. Greenpeace founded. COINTELPRO officially ends.",
  "1972" => "Northern Ireland's Bloody Sunday. First Sudanese Civil War ends. Martial law declared in the Philippines by President Ferdinand E. Marcos. Munich massacre occurs at the 1972 Summer Olympics in Munich, Germany.",
  "1973" => "Yom Kippur War, Beginning of the Watergate scandal. First space station, Skylab, is launched. The Supreme Court of the United States decides Roe v. Wade. Death of Pablo Picasso. First close-up images of Jupiter",
  "1975" => "End of Vietnam War and Fall of Saigon. Death of Francisco Franco; Juan Carlos I becomes King of Spain. Haile Selassie I dies in mysterious circumstances. Dmitri Shostakovich dies. Cambodian Civil War ends with victory for the Khmer Rouge. The Killing Fields murders begin. First Cricket World Cup hosted.",
  "1976" => "First outbreak of the Ebola virus. Death of Mao Zedong. End of Cultural Revolution. Steve Jobs finishes his first significant invention, Apple I. Church Committee.",
  "1977" => "Introduction of the first mass-produced personal computers. Launch of the Voyager spacecraft, currently the most distant man-made objects in the universe. Queen Alia of Jordan is killed in helicopter crash. Tenerife disaster marks the deadliest accident in aviation history. Shaba I conflict involves Safari Club.",
  "1978" => "Invention of artificial insulin. Discovery of Pluto's moon Charon. Independence of Tuvalu. Birth of the first test-tube baby. Cambodian-Vietnamese War begins. Uganda–Tanzania War begins. War in Afghanistan (1978–present) begins. Deng Xiaoping commences Economic reform in the People's Republic of China. Spanish transition to democracy is completed. John Paul I and then John Paul II become Pope.",
  "1979" => "Smallpox eradicated. Soviet–Afghan War begins. Rhodesian Bush War ends. Iranian Revolution and Iran hostage crisis. Shah Reza Pahlavi forced into exile. Arrival of Pope John Paul II in Poland, eventually sparking the Solidarity movement. First close-up images of Saturn. Margaret Thatcher becomes Prime Minister of the United Kingdom. Implementation of China's One child policy. Uganda–Tanzania War ends with defeat for Uganda and the exile of Idi Amin. Cambodian-Vietnamese War ends with the overthrow of Cambodia's Khmer Rouge regime. 1.7 million people known to have been murdered in The Killing Fields. Sino-Vietnamese War. Nicaraguan Revolution. Central Treaty Organization dissolved.",
  "1981" => "Independence of Palau. First orbital flight of the Space Shuttle.",
  "1982" => "Death of Leonid Brezhnev; Yuri Andropov becomes leader of the Soviet Union. First Israeli invasion of Lebanon. Falklands War. Hama massacre in Syria leads to more than 10,000 deaths.",
  "1983" => "GPS becomes available for civilian use. Independence of Brunei. End of dictatorship in Argentina. Second Sudanese Civil War begins. Invasion of Grenada by the United States. Bombing of U.S. Embassy in Beirut.",
  "1984" => "Death of Yuri Andropov; Konstantin Chernenko becomes Premier of the Soviet Union. Beginning of the 1984–1985 famine in Ethiopia and the 1984-85 UK miners' strike. Sino-British Joint Declaration agrees to hand Hong Kong back to China by 1997.",
  "1985" => "End of 1982 Lebanon War.Live Aid. Death of Konstantin Chernenko; Mikhail Gorbachev becomes Premier of the Soviet Union. First use of DNA fingerprinting. End of dictatorship in Brazil.",
  "1986" => "Challenger and Chernobyl disasters. South Yemen Civil War. Launch of the space station Mir. First close up images of the planet Uranus. Return of Halley's Comet. End of dictatorship of Ferdinand Marcos in the Philippines. Iran-Contra becomes public. Assassination of Olof Palme.",
  "1987" => "Stock market crash of 1987. First Intifada between Israel and Palestine begins. World population reaches 5 billion.",
  "1988" => "Perestroika begins. End of the Iran-Iraq War. End of dictatorship of Augusto Pinochet in Chile. Pan Am Flight 103 falls over Lockerbie, Scotland. Myanmar Armed Forces launch a military coup. Construction of the Channel Tunnel begins. George HW Bush is elected President of the United States.",
  "1989" => "Fall of the Berlin Wall; 1989 revolution and collapse of the Soviet Bloc in Europe. Tiananmen Square Massacre in China. End of Soviet–Afghan War. End of dictatorship in Paraguay and first direct Presidential election in Brazil since 1960. Death of Emperor Hirohito, his son Akihito becomes Emperor of Japan. Fatwa issued against Salman Rushdie. Exxon Valdez oil spill. First close up pictures of Neptune. First Liberian Civil War begins.",
  "1991" => "Gulf War ends in US withdrawal and failed uprising. Dissolution of the Soviet Union and independence of 15 former Soviet republics. Boris Yeltsin becomes the first President of the Russian Federation. Ten-Day War in Slovenia begins the Yugoslav Wars. Beginning of the Somali, Sierra Leonian and Algerian Civil Wars. Final end of the Khmer Rouge in Cambodia",
  "1992" => "Maastricht Treaty creates the European Union. Bill Clinton is elected President of the United States. End of dictatorship in Albania and South Korea. End of Salvadorian Civil War. Bosnian War begins. Los Angeles riots over the acquittal of those involved in the beating of Rodney King.",
  "1993" => "Velvet divorce between Czech Republic and Slovakia. Independence of Eritrea. Oslo accords end First Intifada between Israel and Palestine.",
  "1994" => "End of apartheid in South Africa and election of Nelson Mandela. Establishment of NAFTA. First Chechen War begins. 1994 civil war in Yemen. Assassination of Juvénal Habyarimana and Cyprien Ntaryamira triggers the Rwandan genocide. Opening of the Channel Tunnel.",
  "1995" => "Establishment of the World Trade Organization. American terrorist Timothy McVeigh bombs the Alfred P. Murrah Federal Building in Oklahoma City. Srebrenica massacre. NATO bombing raids in Bosnia end the Bosnian War; Dayton Accords signed. Assassination of Yitzhak Rabin. North Korean famine begins. Austria, Finland and Sweden join the European Union.",
  "1996" => "First Congo War begins. First Chechen War ends. First Liberian Civil War ends. End of dictatorship in Taiwan. Dolly the sheep becomes the first successful cloned mammal. The Taliban government takes control of Afghanistan.",
  "1997" => "Tony Blair becomes Prime Minister of the United Kingdom. Transfer of sovereignty over Hong Kong from UK to China. Lottery Uprising in Albania. Kabila ousts Mobutu: Zaire becomes the Democratic Republic of the Congo. Diana, Princess of Wales is killed in a car accident in Paris. Sound barrier broken on land.",
  "1998" => "Osama bin Laden publishes a fatwa against the West. Kenya and Tanzania bombings. Second Congo War begins. Good Friday Agreement brings an end to The Troubles in Northern Ireland. North Korean famine kills an estimated 2.5 million people by this point.",
  "1999" => "Euro is introduced. Kosovo War ends the Yugoslav Wars. Islamist insurgency in Nigeria begins. Hugo Chavez becomes President of Venezuela. Second Chechen War and Second Liberian Civil War begin. Fourth Indo-Pakistani War. Crisis in East Timor leads to 1400 deaths. Columbine High School massacre in Colorado, USA. World population reaches 6 billion.",
  "2001" => "September 11 attacks: Terrorists destroy the World Trade Center in New York City, damage The Pentagon in Washington, DC. War on Terror declared. Afghan War begins. Wikipedia founded. African Union founded. During economic crisis in Argentina government effectively froze all bank accounts for twelve months which led to riots and President de la Rúa's resignation from office. President Joseph Estrada of the Philippines impeached.",
  "2002" => "2002 Bali bombings. Chechen rebels seize theatre in Moscow. America demands Iraq allow unfettered access to weapons inspectors. Guantanamo Bay detention camp is established. Algerian Civil War ends. Rose Revolution in Georgia. Independence of East Timor.",
  "2003" => "Iraq War begins, triggering worldwide protests. War in Darfur begins. The Human Genome Project is completed. Second Congo War ends with more than 5 million dead. Second Liberian Civil War ends. Space Shuttle Columbia is destroyed on re-entry.",
  "2004" => "Enlargement of NATO and the European Union incorporates most of former Eastern Bloc. Union of South American Nations formed. Madrid train bombings. Orange Revolution in Ukraine. Beslan school hostage crisis. Boxing Day Tsunami occurs in Indian Ocean, leading to the deaths of 230,000.",
  "2005" => "IRA end military campaign in Northern Ireland. 7/7 attacks on London Underground. Angela Merkel becomes Germany's first woman Chancellor. Tulip Revolution in Kyrgyzstan. Second Intifada ends. Israel withdraws from Gaza. Cedar Revolution in Lebanon triggered by the Assassination of Rafic Hariri. Second Sudanese Civil War ends. Hurricane Katrina kills nearly 2000 people in the Gulf of Mexico. 80,000 are killed in an earthquake in Kashmir. The Kyoto Protocol comes into effect. Mahmoud Ahmadinejad becomes President of Iran. Death of Pope John Paul II; Benedict XVI becomes Pope. Discovery of Eris.",
  "2006" => "Independence of Montenegro. Second invasion of Lebanon. Mumbai bombings. Ellen Johnson Sirleaf becomes President of Liberia, and thus Africa's first elected female head of state. Execution of Saddam Hussein. The Baiji, the Yangtze river dolphin, becomes functionally extinct.",
  "2007" => "Anti-government protests in Myanmar crushed by ruling junta. Spike in food prices and subprime crisis help trigger global recession. Assassination of Benazir Bhutto.",
  "2008" => "End of Monarchy in Nepal. Barack Obama is elected President of the United States. Cyclone Nargis kills 133,000 in Myanmar. Gaza War begins. 2008 South Ossetia war. Kosovo declares independence, to mixed reaction. Battle of Basra - Iraqi forces crack down on Muqtada al Sadr's Mahdi forces in Basra and Sadr City.",
  "2009" => "Gaza War ends; Gaza blockade continues. Sri Lankan Civil War ends. Election protests begin in Iran. Second Chechen War ends. Boko Haram rebellion begins in Nigeria. Death of Michael Jackson. Burj Khalifa in Dubai, the world's tallest skyscraper, is completed. Great Recession officially ends. Formation of BRICS economic bloc. Treaty of Lisbon ratified.",
  "2011" => "Death of Steve Jobs. Independence of South Sudan. Arab Spring: revolutions in Tunisia, Egypt and Libya follow, as well as uprisings in Yemen and and Bahrain, and protests in several other Arab countries. Syrian civil war begins. Occupy movement inspires worldwide protests. News International phone hacking scandal. A 9.0 earthquake and the meltdown of the Fukushima Nuclear Power Plant. Second Ivorian Civil War ends with the arrest of former president Laurent Gbagbo. Deaths of Osama bin Laden, Muammar Gaddafi, and Kim Jong-Il. Iraq War ends. Riots flare across England. World population reaches 7 billion. 2011 Domodedovo International Airport bombing, 2011 Mogadishu bombing.",
  "2012" => "2012 Northern Mali conflict, the MNLA declares Azawad an independent state. Yemeni President Ali Abdullah Saleh steps down. 2012 Benghazi attack leads to the death of US ambassador J. Christopher Stevens. The Higgs boson is discovered. Hurricane Sandy kills 209 people in North America, while Typhoon Bopha kills over 1,600 in the Philippines. Skydiver Felix Baumgartner becomes the first person to break the sound barrier without a vehicle. Central African Republic conflict (2012–13) begins. UN Climate Change Conference agrees to extend the Kyoto Protocol until 2020. Israel launches Operation Pillar of Defense against the Palestinian-governed Gaza Strip. 2012 Guinea-Bissau coup d'état.",
  "2013" => "The French military intervenes in the Northern Mali conflict. Chelyabinsk meteor. Resignation of Pope Benedict XVI, Pope Francis becomes Pope. Terrorist attacks occur in Boston and Nairobi. 2013 Savar building collapse in Bangladesh. Edward Snowden releases classified documents concerning mass surveillance by the NSA. President of Egypt Mohamed Morsi is deposed by the military in a coup d'état. Croatia becomes a member of the European Union. The Euromaidan protest begins in Ukraine. A chemical attack in Ghouta, Syria is blamed on President Bashar al-Assad. Typhoon Haiyan kills nearly 6150 people in the Philippines and Vietnam. Death of Hugo Chávez.Conflict begins in South Sudan. Uruguay becomes the first country to fully legalise cannabis. End of 2012–2013 Cypriot financial crisis.",




}


a.each do |key,value|
  temp_date = key.dup
  temp_date = temp_date.to_s
  temp_date = temp_date.insert(0,"1 January ")
  temp_date = Date.parse(temp_date)
  Post.create( user_id: User.first.id,
               post_title: value[0..50],
               post_text: value,
               post_date: temp_date
               )
end
